databases:
  - name: django_render_vr_rev
    region: singapore
    plan: free
    databaseName: django_render_vr_rev
    user: django_user

services:
  - type: web
    name: django_render_vr_rev
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn mysite.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_vr_rev
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true