# Generated by Django 3.1.11 on 2021-06-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_caregory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caregory',
        ),
    ]
